# Generated by Django 2.2.3 on 2019-07-18 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='linkedin',
            field=models.URLField(blank=True),
        ),
    ]
