# Generated by Django 2.2.3 on 2019-07-23 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0002_member_linkedin'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='city',
            field=models.CharField(default='Lexington', max_length=60),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='member',
            name='state',
            field=models.CharField(default='KY', max_length=30),
            preserve_default=False,
        ),
    ]
