# Generated by Django 2.2.3 on 2019-07-29 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0003_auto_20190723_1529'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=60)),
                ('state', models.CharField(max_length=30)),
                ('latitude', models.DecimalField(decimal_places=7, editable=False, max_digits=12)),
                ('longitude', models.DecimalField(decimal_places=7, editable=False, max_digits=12)),
            ],
        ),
        migrations.AddField(
            model_name='member',
            name='latitude',
            field=models.DecimalField(decimal_places=7, default=38.0406, editable=False, max_digits=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='member',
            name='longitude',
            field=models.DecimalField(decimal_places=7, default=-84.5037, editable=False, max_digits=12),
            preserve_default=False,
        ),
    ]
