# Generated by Django 2.2.3 on 2019-08-05 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0004_auto_20190729_1915'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='company',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='member',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='member',
            name='position',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
