# Generated by Django 2.2.4 on 2019-08-21 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0011_member_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='image',
            field=models.ImageField(blank=True, default='https://ta-alum-app.s3.amazonaws.com/images/Skye.jpg', upload_to=''),
        ),
    ]
